### ISSUE TITLE
AWS Educate Not Providing Credly Badges

### ISSUE THREAD

**Issue by Safnaj** [CloudNativeStudyGroup/Free-Credly-Badges#11]
As far as I know AWS educate courses wont give you credly badges. Pls verify and remove the below section. 

![Screenshot 2024-12-10 at 3 40 09 PM](https://github.com/user-attachments/assets/3959408b-13dd-4bc9-b249-f8a01509b386)

**Comment by nvsajeeva** [comment]
Thanks @Safnaj . I will have a look :)

**Comment by nvsajeeva** [comment]
@Safnaj I see the corresponding credly badges. Do you mean they do not offer those badges currently?

https://www.credly.com/org/amazon-web-services/badge/aws-educate-introduction-to-cloud-101
https://www.credly.com/org/amazon-web-services/badge/aws-educate-getting-started-with-storage

**Comment by Safnaj** [comment]
If they are providing Credly badges, that should be okay.
