### ISSUE TITLE
Some AWS courses no longer have badges

### ISSUE THREAD

**Issue by bcuz** [CloudNativeStudyGroup/Free-Credly-Badges#5]
Object Storage and Block Storage no longer have the assessment to get the badge

Block Storage example:
https://explore.skillbuilder.aws/learn/public/learning_plan/view/93/storage-learning-plan-block-storage

**Comment by nvsajeeva** [comment]
Removed. Thanks @bcuz 
https://github.com/CloudNativeStudyGroup/Free-Credly-Badges/pull/7
